server:
  port: 8009
rss:
  feed:
    sources:
      -
        name: 少数派
        url: https://sspai.com/feed
      -
        name: 机核网
        url: https://www.gcores.com/rss
      -
        name: 异次元软件
        url: https://feed.iplaysoft.com
      -
        name: 36氪
        url: https://36kr.com/feed
      -
        name: 今日话题-雪球
        url: https://xueqiu.com/hots/topic/rss
