server:
  port: 8001
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/scan-login?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver