server:
  port: 8101
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/rorm_rmp?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.194.162
    port: 6379
    jedis:
      pool:
        # 最大连接数
        max-active: 20
        # 最大阻塞等待时间(负数表示无限制)
        max-wait: -1
        # 最大空闲时间
        max-idle: 5
        # 最小空闲时间
        min-idle: 0
logging:
  level:
    com.chenx.mapper: debug